### ISSUE TITLE
Legal Action Notices Received 

### ISSUE THREAD

**Issue by talhaobject90** [tgalal/yowsup#1004]
Hi Tarek,

Your github and repositories are awesome. I am very glad to find such a passionate person over the network. For about a couple of years i am investigating the possibilities to utilize whatsapp service to write custom applications. I have been successful a couple of times. I have written some scripts for reminder applications by utilizing your yowsup repository for my whatsapp registration and https://github.com/WHAnonymous/Chat-API for sending messages.

But now I have a concern relating to License violation to Whatsapp legal terms , As WHAnonymous received  a notice from Whatsapp lawyers for ceasing the operations as they found it violating their terms.
(http://www.docdroid.net/gWpFsXz/whatsapps-cease-and-desist-and-demand-against-chat-api.pdf.html) 

I am planning to add a notification service to members of a website through whats app , for which i am planning to use your masterpiece (yowsup).

So I would like to confirm that your repository and it's utilization wouldn't violate whatsapp legal terms in any way. 

I Kindly request you to take some time from your busy schedule to  respond to my query , because i don't want any violation notices from whatsapp in future.
 
Advance thanks.
talhaqqq@gmail.com

**Comment by tgalal** [comment]
According to WhatsApp, yowsup violates their legal terms. I also got a cease and desist.

**Comment by aesedepece** [comment]
We at wha.tools have also received one. This was my "kind" answer:

> Dear Mr. Xxxxxxx,

> I am writing to you with respect to WhatsApp claims against me arising from my alleged contribution to the development, promotion and operation of the Whatools service.

> I am fully aware that the key for the success of the WhatsApp service has been keeping the
service completely ad-free. They do not want their users to be bothered with SPAM, undesired
correspondence or propaganda.

> I am a user of the WhatsApp service myself and I do not want my inbox to be flooded with
unsolicited messages from unknown senders either.

> WhatsApp has very strong rules on what users can do and what they can't with the service. I
consider some of those terms to be rather abusive, but nevertheless I strongly believe some others
are quite fair as they seek to ensure a balance between individuals and companies using their
service.

> When communicating with my service's users, I always endorse and enforce those same "fair use"
terms, which among others, are:

> - Never sharing illegal or offensive content.
- Never sending too many more messages than a human being could write.
- Trying not to send many messages to people who doesn't have their number in their phone
list or have never sent them a message.

> My service has a form for reporting abusive use and undesired communications. Every time
a user has been reported, I have quickly examined the account and proceeded to service suspension if the misbehavior was proved.

> As my company is based in Spain, my service complies with the "Spanish Law of Protection of Personal Data", the "Spanish Law of the Information Society Services" and equivalent EU directives. Those laws are the most data-protective in the world and forbid anyone to send messages to people who hasn't requested them.

> Your first claim is that Whatools is using WhatsApp for commercial purposes, but in fact it
is not. Indeed the ones using WhatsApp are the users of my service. I do not own any of my
service's users' WhatsApp accounts and they are the ones who signed your Terms of Use, not me.
Whatools is a mere tool for accessing the WhatsApp service, just like any smart phone or operating
system allowing such access is.

> Your second claim is that I am “charging others to use the WhatsApp service throughWhatools”. I am not charging users for accessing your service. They can do it for free by using our
trial accounts program. They can register as many accounts as they want and never pay a single cent to me if they do not want to. In addition, premium users do not pay for access but for my support service and the convenience of not having to register their accounts every 20 days.

> In your third claim, you accuse me of operating a service “that permits others to send bulk
messages or spam”. Nothing could be further from the truth: I have always adopted all the
measures required by the aforementioned laws and informed to my service's users that they are not allowed to send bulk messaging or spam on notice that accounts infringing that rule will be
immediately disabled and banned from my service.

> Regarding your fourth claim, about “developing and distributing a service that permits
others to solicit WhatsApp users for commercial purposes”, I suggest you to read a little Spanish
legislation. We have plenty of case laws stating that devisers of technological tools can not be
blamed for the illicit use others could make of those tools, just like the inventor of the gun or the
knife are not to be blamed for murders. Thus, Whatools' activity is not only neutral and perfectly
legal, moreover it is protected by article 38 of the Spanish Constitution of 1978. For a maybe more
familiar case, you can also take a look at Sony Corp. of America v. Universal City Studios, 464 U.S.
417 (1984).

> In your fifth claim, you say Whatools “facilitates the use of the WhatsApp registration
system to generate credentials for and authenticate unauthorized clients”. If you have taken the time to check how my service uses the WhatsApp registration system, you must have noticed for sure that I tell my service's users that by accessing Whatools or the WhatsApp registration system, they are accepting the WhatsApp Terms of Use. I can not differentiate an “unathorized client” from an authorized one, that is WhatsApp's job, not mine.

> On your sixth claim, you must perfectly know that according to Sec. 103(f) of the DMCA
and Article 6 of the 1991 EU Computer Programs Directive, any technological measures
circumvention that might have been carried out for the creation of Whatools is totally legitimate as
its purpose is "enabling interoperability of an independently created computer program with other
programs" and "indispensable to obtain the necessary information to achieve the interoperability of
an independently created program with other programs [...] to make it possible to connect all
components of a computer system, including those of different manufacturers, so that they can work together". The public release of information acquired by those means is also permitted "solely for the purpose of enabling interoperability of an independently created computer program with other programs".

> As of your accusation of “exploiting WhatsApp’s Service, undermining the goals of
WhatsApp, and intruding upon and undermining the service experience of the community of
WhatsApp users”, I have to say that there is no way in which Whatools could have harmed the
WhatsApp service or community. Whatools targets a niche that the WhatsApp company does not
(the B2B and B2C sector). Thus Whatools helps WhatsApp to reach new markets and constantly
increase their user base. In addition, I pay the WhatsApp annual fee for users whose WhatsApp
accounts expire while their subscription to my service is in force. This policy ensures WhatsApp an
effective income, as many WhatsApp users often avoid paying such fee.

> I perfectly know that this move from Facebook comes after their plans for monetising the
WhatsApp service by gradually allowing businesses to use their platform by paying a premium fee.
So stop pretending that your demands aim to protect their users and their “service experience”. Your demands only want to eliminate competition. Threatening rival companies is a form of dominant position abuse that goes against EU antitrust rules, specifically Article 102 of the Treaty on the Functioning of the European Union.

> Answering your demands, these are the actions and precautions that you can immediately
expect from me:

> - Start the progressive closing of the Whatools service, as you have already showed off your
greed and I do not want further problems with soulless monsters like the WhatsApp
company,
- Cease using any name or logo confusingly similar to those registered by the WhatsApp
company,
- Preserve any information potentially relevant to the issues addressed in your letter.

> Regarding your demand about “disgorging” all profits I may have obtained from the
operation of Whatools, I have to inform you that such service has an income shortfall, so all I can
“disgorge” is a heap of debt. I will be eager to “disgorge” that to WhatsApp.

> You also demand me to compensate “WhatsApp for the damages it sustained from my
commercialization and operation of Whatools”. As I exposed before, I have not only not damaged
WhatsApp but irrefutably benefited them. Are they willing to compensate such profit?

> Finally, I have to thank Facebook for closing my account. I heard it was quite difficult to get
your account completely deleted from their service, but it has been quite easy indeed. Good job.

> I expect you to respond within 48 hours of your receipt of this letter. If you ignore this letter,
I will understand that you agree and consider my taken actions and precautions enough to discharge me from any legal responsibility following your demands.

>Sincerely,
Spencer Truman

No response was received after 48h.
