### ISSUE TITLE
ERROR:yowsup.layers.axolotl.layer:No valid sessionsBad Mac!

### ISSUE THREAD

**Issue by yniv** [tgalal/yowsup#1130]
Hi all,
After sometime I run the process and sending & receiving messages I started to get this error:
ERROR:yowsup.layers.axolotl.layer:No valid sessionsBad Mac!

for a specific number. What doe's it mean and what should i do?

**Comment by jmt-cash** [comment]
Same problem here, please help! :-(

**Comment by janboll** [comment]
Based on my observation this error-messages happens on the receipt of a message. Deleting the corresponding entries from the axolotl db doesn't help.
What worked for me was sending a message to the client that sent you the message causing this error. To find out the number that sent you the message you have to enable the debug-mode.

**Comment by jmt-cash** [comment]
Thanks, i figured out this trick by accident when I started the echoclient to test, but thats not a real solution when you run this client kind of productively.

**Comment by bdbais** [comment]
same problem here... No valid sessionsBad Mac  how to debug it ?

**Comment by bdbais** [comment]
DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed Axolotl Layer
WARNING:yowsup.stacks.yowstack:Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Media Layer - Iq Layer - call Layer
DEBUG:yowsup.stacks.yowstack:Constructed Interface Layer
DEBUG:yowsup.layers.network.layer:Connecting to e4.whatsapp.net:443
DEBUG:yowsup.layers.logger.layer:tx:
<stream:features>
<readreceipts>
</readreceipts>
<groups_v2>
</groups_v2>
<privacy>
</privacy>
<presence>
</presence>
</stream:features>
<receipt to="383939566669@s.whatsapp.net" type="retry" id="qihH1slSp1mhB">
<retry count="1" v="1" t="1450766993" id="qihH1slSp1mhB">
</retry>
<registration>
~▒▒
HEX:7eead808
</registration>
</receipt>

DEBUG:yowsup.layers.logger.layer:rx:
<message from="383939566669@s.whatsapp.net" notify="bdbais" offline="3" type="text" id="qihH1slSp1mh9" t="1450767000">
<enc count="1" type="msg" v="1">
3
!.k▒▒▒▒▒▒v▒

t߭▒n▒_▒Ѩ]▒▒▒vF▒"▒▒▒{ǑX(%r▒/P▒▒qL▒▒▒z▒
HEX:330a21052e6b881ecef4c9dd01fa76ae0b0a74dfadd46efe065fe881d1a85dffecf0764610f40618022210f9ddf3b87bc79158282572932f50f5c0714cc9fe11a67a8a
</enc>
</message>

ERROR:yowsup.layers.axolotl.layer:No valid sessionsBad Mac!
------------
I'm blocked.

**Comment by pirmanji** [comment]
I just had the same issue. After just deleting the whole folder containing the axolotl.db and reconnecting yousup everything works fine again. Seem's has something todo with upgrading yowsup and maybe old datas in axolotl.db?

**Comment by gbarba** [comment]
There are some duplicated issues, at least  #1405 #1436 #1378

I answer here because is the oldest of open issues related to this error.

We observed a repeatable scenario when this error happens:

1. Comunicate with user (for example, Guillem)
2. **Stop yowsup and clean keys**
3. Start yowsup => regenerate prekeys
4. User (Guillem) send messages to yowsup =>  "No valid sessionsBad Mac!" is raised and messages are not received
5. Send message from Yowsup to user => it is received
6. Send messages from user to Yowsup => is is received

What is happen here is that user and yowsup have been generated session keys for they communication.
When the keys (sqlite database in ~/.yowsup directory) are deleted and generated again, yowsup loose the hability to decrypt the messages of user, because it is using the old keys of yowsup.
When yowsup sends a message to user, it makes that session key are updated and yowsup again able to decrypt the user's messages.

Probably the code here (https://github.com/tgalal/yowsup/blob/master/yowsup/layers/axolotl/layer.py#L236) tries to solve this situation... or another similar (because I think there are other situations when this error is raised) but this code doesn't solves the problem.

Our ugly workaround is sends an empty message to user but provably there is some kind of protocol message that we can send to force resync session keys... but we can't find it ( @tgalal help please ;-))

**Comment by shacharlovett** [comment]
I followed your solution (including sending a message to the user). But now I get the following error:

...
File "/usr/local/lib/python3.5/dist-packages/axolotl/sessioncipher.py", line 88, in decryptMsg
    return plaintext.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 4: invalid continuation byte

**Comment by DreamFlasher** [comment]
> @janboll What worked for me was sending a message to the client that sent you the message causing this error. To find out the number that sent you the message you have to enable the debug-mode.

This worked for me too, could this maybe be fixed? Like when there is an incoming message which throws that exception automatically let yowsup send them a message "ERROR: Your message was not received, please resend it."

**Comment by gbarba** [comment]
Send this message from axolotl.layer is not a good option because the end user maybe doesn't understand english.

What we have done is raise an exception in axolotl/layer.py
https://github.com/metis-ai/yowsup/commit/7a1b3aeb512cc3386519527049845493372d89b8#diff-4cde7fef8ed0272b5797863ea19fe29eR248

This is captured in the app that uses yowsup and sends a customized message.
We didn't do a PR because we are waiting that whatsapp ends the transition to end-to-end encryption and see whats the behaviour then

**Comment by DreamFlasher** [comment]
What happens if one sends an empty message? Is that actually displayed by whatsapp or does that get filtered out? Can we send any message to the user which is not shown? (Just to establish the handshake)

**Comment by shacharlovett** [comment]
It seems to show an empty message (on an android phone, running latest
whatsapp version)

**Comment by tgalal** [comment]
This is [not a problem](https://github.com/tgalal/yowsup/issues/1436#issuecomment-214690516)
