### ISSUE TITLE
Need help in using different "env_android" values

### ISSUE THREAD

**Issue by ghost** [tgalal/yowsup#1168]
I don't understand much about what these `env_android.py` or `env_s40.py` do? They probably are used to give Android OS environment (or S40) so that our requests looks being sent from an Android device?

How can I update these `_SIGNATURE`, `_MD5_CLASSES`, `_KEY` etc to something else? Let's say I have my own Android device and I want to use that device's info here. So, how do i do that?

Regards
##

**Comment by mgp25** [comment]
1. Check other issue, it's explained.
2. To obtain md5 classes, you can use a tool i did (check my repos)
3. That is only used while registering, and it will appear in the User Agent.
4. Version is also used in the resource (protocolo stuff)

Conclusion: it doesnt matter if you change device, and i recommend to stick with the data we provide so all users can enjoy the API without any problem

Regards

**Comment by HackTheDay** [comment]
I'm looking for solution for the "number getting blocked issue" and I assume may be it's the device Info which is getting the numbers blocked.

Because if you change your number so many times in a hour on a single mobile device, then you're most likely to get blocked.

But let's say ~20 people users same network (ip address) and registers from different devices, almost in same span of time, then they are less likely to get blocked. So, probably issue is with different devices for different numbers instead of ip address.

So, need a proper solution here, i guess.

Regards

**Comment by mgp25** [comment]
I think you are not using the API for personal usage, and that goes against WA and API EULA.

**Comment by HackTheDay** [comment]
No, I'm using for personal use only. But, I'm just curious about learning the role of IPs or Devices in "numbers getting blocked issue" and that's it.
So, I'm interested in knowing what could be cause and fixing it, so that `Yowsup` community can benefit. :-)

So, @mgp25 can you please give details about how to extract `MD5` or `Signature` or any other info from any device? What was the tool you're talking about?

**Comment by ykguCoder** [comment]
@ghost @mgp25  Did you solved the question of update these _SIGNATURE,_KEY etc?
