### ISSUE TITLE
axolotl.db file and dir doesn't regenerate after dir erase

### ISSUE THREAD

**Issue by yniv** [tgalal/yowsup#1170]
I erased the ~/.yowsup/NUMBER dir because of untrusted identity and now when i restart yowsup it doesn't regenerate.... how can i make it regenerate again?
also, what can I do if someone switched phone and now I keep getting Untrusted Identity?
##

**Comment by lallex1848** [comment]
I know this is from way back... but what was the solution? i am running into the same error here, it won't regenerate axolotl.db and therefore no key generation. Has anybody solved this?

**Comment by Nicos-git** [comment]
Try "find / -name axolotl.db" command to verify you removed the correct file.
There might be a different file if you're using yowsup as xmpp-backend

**Comment by lallex1848** [comment]
ok, thanks for the answer! I tried this on two different machines, and it gave back axolotl.db files in root home folder on one machine and in user home folder on the other... i am guessing permissions issue, because it won't work on environment with axolotl.db in user home folder... would appreciate more insights here
