### ISSUE TITLE
whatssap ban my phone number

### ISSUE THREAD

**Issue by minimaldev** [tgalal/yowsup#1344]
whatssap ban my phone number how i can prevent this after sending some messages
i got this error
{"status":"fail","reason":"blocked"}

my question is why yowsup ban my phone number i got two numbers banned

**Comment by jlguardi** [comment]
Probably you are using something that whatsapp consider SPAM. My experience is: 10-15 messages to people who haven't you as contact, you will be banned.
I've got multiple phones more than 20 used for notifications to registered people (not for communicate to unknown people) and I don't have problems.

**Comment by loffy** [comment]
Dear,
Today after some messages exchanged with a contact, just for testing I got my number banned. I didn't do any spam or ads. Now if I read the conditions of violation of whatsup service the only thing related to a violation is the use of third part software. So practically if I use yowsup I 'll be always banned because of use of unauthorized client software. Is it the reason in your opinion? If I'm wrong what could be the procedure to avoid to be blocked? I read a lot of different behavior on blocking situations and I'm confused on the rules to pay attention in using yowsup avoiding the ban from whatsup.

**Comment by abloch** [comment]
+1 it could be beneficial to have a set of rules on how to use yowsup without been banned

**Comment by loffy** [comment]
Here the reason because I was banned. It happened because I used a third party application and not because I spammed someone. Then is impossible using yowsup without be blocked, sooner or later you will be banned at any time even if you try to follow all the suggestions given in the other posts.

Email sent to me from the whatsup technical support

**> ##- WhatsApp Support -##
> Hi,
> 
> Sorry for the delay! We have received many emails recently, and we do our best to answer them all. Thank you for your patience.
> 
> Your WhatsApp account was banned because you violated our Terms of Service and were using an unauthorized application and/or unsupported device.**
