### ISSUE TITLE
Receiving messages from new numbers

### ISSUE THREAD

**Issue by eniomaxson** [tgalal/yowsup#1349]
Hi guys!
I have an EchoLayer inheriting from YowInterfaceLayer.
In that layer i implemented @ProtocolEntityCallback("message")  and @ProtocolEntityCallback("receipt").
The callback "message"  just is fired when the received message is from  numbers that i were alredy used with  yowsup-cli. 
These messages  of new numbers must be receive on "message" callback or exist other event to it.

**Comment by jlguardi** [comment]
All messages are recieved in the same callback.

If yowsup-cli works correctly, the problem is in your EchoLayer and probably with the encryption layer (YowAxolotlLayer). Attach your stack.py and layer.py and check that you are enabling encryption.

By the way, you can tray to remove axolotl.db and start again your app.

**Comment by eniomaxson** [comment]
I removed axolotl.db and works.
Thanks!
