### ISSUE TITLE
Editing a demo, don't see any changes

### ISSUE THREAD

**Issue by yhoba** [tgalal/yowsup#1370]
Hello guys, i'm new to Yowsup. I found out to register and get Yowsup working. But when i edit the demo files, for example the echo client, and run Yowsup in the terminal of my Raspberry is doesn't seems to be change. 

Are the demo files in another directory of do i have to update the terminal cache somehow?

**Comment by Stepkaa** [comment]
Files are in, for example: usr/local/lib/python2.7/dist-packages/yowsup2-2.4.48-py2.7.egg

**Comment by thundergreen** [comment]
I'm still wondering why u use the CLI instead of a transport manager like
spectrum2 and transwhat ..works perfectly for me if someone needs help to
setup this bundle .....I'll provide a help page soon were u can see install
and config tutorial for the pi.

Just shortly my setting:
Raspberrypi 3
Ejabberd 16.02
Spectrum2 latest version (built from source)
Transwhat using yowsup
A transport registration for WhatsApp and other transports for xmpp is
available at:

https://emevth.no-ip.biz

Thorsten Fröhlich
Am 17.03.2016 22:14 schrieb "Mark B" <notifications@github.com>:

**Comment by yhoba** [comment]
@Stepkaa maybe it's stupid: but how to edit or update an .egg file?

**Comment by Stepkaa** [comment]
@yhoba .egg is just an archive. Way I did it: created an empty folder called yowsup2-2.4.48-py2.7.egg, extracted all files from original .egg archive to the folder.

**Comment by yhoba** [comment]
@Stepkaa Thanks!
