### ISSUE TITLE
Delay in receiving messages

### ISSUE THREAD

**Issue by teehamaral** [tgalal/yowsup#1423]
No error is displayed, however, sometimes the messages arrive instantly the moment the messages take about minutes to being received. I've tried everything, removed the axolotl database to be created again, the number was reauthenticate in whatsapp using yowsup, but the delay persists at certain times, and back to normal (for a while) without having done anything. Someone is going through something that can help me?

**Comment by pag16** [comment]
yes i am also facing this ..

**Comment by pag16** [comment]
@jlguardi your help will be very nice in this matter.

**Comment by thundergreen** [comment]
Same issue here ..I also got receipt confirmation since a long time and
then nothing .I already  posted my debug .I guess there's an axolotl
problem.but it's weird cause I can receive messages but randomly and not
constantly .but I know that jlguardi is working on this

Thorsten Fröhlich
Am 29.03.2016 20:07 schrieb "pag16" <notifications@github.com>:

**Comment by pag16** [comment]
@thundergreen you get a single tick right? and then no message for a long time?
but not like a double tick?

**Comment by thundergreen** [comment]
What donu mean  with tick? I got two times a hook in conversations that my
message was sent.then nothing anymore.I'm using transwhat . but
yes.sometimes after hours some messages are received ... And I don't
understand why ;)

Thorsten Fröhlich
Am 29.03.2016 21:17 schrieb "pag16" <notifications@github.com>:

**Comment by pag16** [comment]
@thundergreen i see ..

**Comment by jlguardi** [comment]
In my case is due to un-ack' group messages and acks.
However I can't send a valid receipt. First I thought that was due to group jid change but I can't either changing jid parsing. 
Related with https://github.com/jlguardi/yowsup/issues/9
Could somebody try chatApi and see if correctly sends receipts and marked I official clients?

**Comment by freelo** [comment]
@jlguardi 
I don't know the details, but this small patch made some reappearing receipts of mine go away (id also has 'A' instead of '-'):
```
--- a/yowsup/layers/protocol_acks/protocolentities/ack.py
+++ b/yowsup/layers/protocol_acks/protocolentities/ack.py
@@ -8,7 +8,7 @@ class AckProtocolEntity(ProtocolEntity):

     def __init__(self, _id, _class):
         super(AckProtocolEntity, self).__init__("ack")
-        self._id = _id
+        self._id = _id.replace('A','-')
         self._class = _class

     def getId(self):
```

**Comment by tgalal** [comment]
Fixed
