### ISSUE TITLE
is there a way to disable personal messages?

### ISSUE THREAD

**Issue by e0xify** [tgalal/yowsup#1429]
Hi,

i dont want to send or recieve personal messages, only that ones in group, is there any piece of code i can change to get it done?

many thanks

**Comment by jlguardi** [comment]
As far as I know, it is impossible at whatsa.. config level.
Moreover, you can't ignore personal messages due to after 5 unreceipt messages connection is closed. So, get personal messages and ack them without read and manage group messages.
De: Rene K.
Enviado: jueves, 31 de marzo de 2016 10:01
Para: tgalal/yowsup
Responder a: tgalal/yowsup
Asunto: [tgalal/yowsup] is there a way to disable personal messages? (#1429)


Hi,

i dont want to send or recieve personal messages, only that ones in group, is there any piece of code i can change to get it done?

many thanks

---
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/tgalal/yowsup/issues/1429
