### ISSUE TITLE
[solved] Register failed - Discotel (Vodafone) - yowsup-cli v2.0.15

### ISSUE THREAD

**Issue by ds2k5** [tgalal/yowsup#1437]
Hi,
my Location is germany, Provider is: discotel (Vodafone Network)

sudo yowsup-cli registration --requestcode sms --phone 49152xxxxxxxx --cc 49 --mcc 262 --mnc 02
yowsup-cli  v2.0.15
yowsup      v2.4.102

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

INFO:yowsup.common.http.warequest:{"status":"sent","length":6,"method":"sms","retry_after":65,"sms_wait":65,"voice_wait":65}

status: sent
retry_after: 65
length: 6
method: sms

What did i wrong ?
Thanks

OS: Ubuntu 15.10 (64bit)
Tryed like in http://wiki.pidgin-im.de/doku.php?id=protokolle:whatsapp  declared

**Comment by jlguardi** [comment]
Update your code to latest release.

De: ds2k5
Enviado: viernes, 1 de abril de 2016 11:03
Para: tgalal/yowsup
Responder a: tgalal/yowsup
Asunto: [tgalal/yowsup] Register failed - Discotel (Vodafone) - yowsup-cli v2.0.13 (#1437)


Hi,
my Location is germany, Provider is: discotel (Vodafone Network)

$ sudo yowsup-cli version
yowsup-cli v2.0.13
Using yowsup v2.4.48


sudo yowsup-cli registration --requestcode sms --phone 4915253413302 --cc 49 --mcc 262 --mnc 02
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"old_version"}

status: fail
reason: old_version

What did i wrong ?
Thanks


OS: Ubuntu 15.10 (64bit)
Tryed like in http://wiki.pidgin-im.de/doku.php?id=protokolle:whatsapp  declared


---
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/tgalal/yowsup/issues/1437

**Comment by ds2k5** [comment]
thanks no it works!
