### ISSUE TITLE
Number blocked while broadcasting

### ISSUE THREAD

**Issue by pushkardravid** [tgalal/yowsup#1452]
I am trying to send an image in bulk. For that I have a list and I am iterating the send function over that list. However the number gets blocked after I send it to 17 receivers or so. So what steps should be taken so as to avoid getting blocked. I have to send the image to around 10000 people. Any help would be appreciated.

**Comment by freelo** [comment]
You confused title and description. Please be nice and:
(a) Don't send spam through any medium.
(b) Edit this issue so that it has a concise title and a meaningful description, including:
 -Your current strategy
 -Your attempted solutions

**Comment by freelo** [comment]
Have you seen #1441 ? There seems to be a BroadcastTextMessage entity, maybe there is a similar option for media messages.

And have you considered introducing a delay between your messages? If you are OK with 3h total runtime, 1 second delay after each message could help (though I haven't tested).

**Comment by mgp25** [comment]
wtf? No way! please dont support spammers.

We don't support any kind of spam or bulk messaging or whatever related to it.

**Comment by maruen** [comment]
Hi @pushkardravid 

Did you solve this issue?
I'm in need in something similar.
Would be very thankfull to you if you could help on that also.

**Comment by freelo** [comment]
I think mgp25 is right. Though one could find legitimate reasons to send 10k messages, it should be avoided to assist in achieving that goal. A spammer is either a good one (which annoys millions of people every day), or it is a bad one that needs help. If it is a bad one, hopefully he will not get any help and never seriously start spamming. Any help on this topic may be abused by a wannabe spammer, since it is a public discussion.

**Comment by Gab0** [comment]
Sending messages to people who don't have you on their contact list allow them to click "this is spam" upon receiving them, so if they are 10k friends just do it. If not, it takes like five people reporting as spam to get you banned, so..

**Comment by thundergreen** [comment]
I think it was mentioned here several times.this open source project is not
for spamming and commercial usage.that's why WhatsApp changes API that
often! Stop doing these things guys or do u want they close and change
their api?  Here are a lot of people who use this repo for learning and
private purpose

Thorsten Fröhlich
Am 04.04.2016 18:34 schrieb "Gab0" <notifications@github.com>:
