### ISSUE TITLE
Authentication Error, Not Authorized

### ISSUE THREAD

**Issue by parthpower** [tgalal/yowsup#1463]
I did the registration from a new phone number which never been registered to the WhatsApp before, logged into the CLI demo, sent some messages and it immediately disconnected. Now when I try to login with the same credentials I get `general: Login Failed, reason: not-authorized`.

I tried to register again to the same number and I'm getting `INFO:yowsup.common.http.warequest:{"status":"fail","reason":"blocked"}`

PS: I'm guessing WhatsApp doesn't like any third-party lib.

**Comment by jlguardi** [comment]
Yes, whatsapp doesn't like yowsup. However, I've never been banned an I've several lines working. But you will be banned if spam (more than 10 messages to recipients that don' known you) or if same message is always sent (with e2e I think this check will disappear).

**Comment by mgp25** [comment]
The 'check' won't dissapear, end-2-end encryption only ciphers the content, the rest remains the same. All 'checks' are server side.

If you code correctly, you wont be blocked, i have one number that hasnt been blocked for 2 years now.

Regards

**Comment by yurmax** [comment]
Blocked after 2 messages. 
I tried two cards of different operators.
I think this is whatsapp bans, this is not a yowsup problem.

**Comment by ronromer** [comment]
Hi @jlguardi what is the secret?

I have been blocked about 10 times, I'm not sending spam, not message e2e, just to a groups

Regards,
Rony

**Comment by jlguardi** [comment]
@mgp25 when I said that the check will disappear, I mean that entropy can't be measured in encrypted messages. 
@ronromer see mgp25/chatApi wiki where good practic practices are introduced. Don't start too many chats fro your bot (10 is too match). Sync your contacts...

**Comment by parthpower** [comment]
@mgp25 I was using the Yowsup built in CLI demo, which I guess, has proper code.
@jlguardi Before the number was blocked, I happen to send exactly 2 messages saying "lol" to myself (my other number which was in the contact list).
I think there should be some kind of warning message in README.md

**Comment by mgp25** [comment]
@parthpower im sorry to tell you but Chat API is more update and stable, at least for now.

And it doesnt matter which one you use, if you use it wrong you will be blocked

**Comment by minimaldev** [comment]
how many times i need to Sync your contacts 
every chat mesage? 
when i receive message for my contact

**Comment by McBacker** [comment]
"@mgp25 If you code correctly, you wont be blocked, i have one number that hasnt been blocked for 2 years now."

Which steps the code must follow?

Thank you

**Comment by minimaldev** [comment]
@McBacker what are you doing correctly for prevent the ban because i blocked more than 5 sims

**Comment by ksulanc** [comment]
@McBacker i would also know what you doing correctly, because i synced my contact in der CLI with the command "/contacts sync numbers-comma-separarted" and also was not sure if it is enougth to do this one time, so i experimentally added in the "32_yowsup.pm" Modul on my FHEM Server following Code in the "sub yowsup_Parse($$)" after the line "yowsup_Write( $hash, "/presence name .....":

`yowsup_Write( $hash, '/contacts sync numbers-comma-separarted' );`

I wanted to be sure that the contacts keep synced every time. So after 5 min testing and 5min afk, i got blocked also with my secound number (it's my homenumber to doing automation things like status of the room thermostats or sending commands to them, it worked perfectly for 6 months but after the 1st April, it is like that Whatsapp or whatever is still fooling us :D ).

Maybe some of you guys have a advice or a fix for this blocking problem.

**Comment by thundergreen** [comment]
It's like a purge if third party Users. I think Whatsapp will make its
rules Straight  and will try everything for third party users not to use it.

Thorsten Fröhlich
Am 16.04.2016 18:40 schrieb "K. S." <notifications@github.com>:
