### ISSUE TITLE
How does WhatsApp `End to End Encryption` affect the future of Yowsup?

### ISSUE THREAD

**Issue by drmaposa** [tgalal/yowsup#1476]
Recently WhatsApp announced a new piece of technology to their system dubbed 'End to End Encryption'. My question is "How does this going to affect YOWSUP client". Is this what we should also look at or it affects other native clients like Android, iPhone Windows phone etc.

Im really worried guys???

**Comment by mgp25** [comment]
Yowsup has e2e encryption implemted already since one year ago. No need to worry.

It is true that there are some missing parts and a new way of authing (WA 2.0). Eventually we'll do a downtime in the API, this will be done to kick put all spammers and people that uses the API with commercial purposes.

Aside of that, you dont need to worry about anything

Regards
