### ISSUE TITLE
[wa16] Fixed some bugs.

### ISSUE THREAD

**Issue by Gab0** [tgalal/yowsup#1499]
I think it's working 100% now, finally...
https://github.com/Gab0/yowsup.git

Instructions:
- Clear the .db file.
- Talk to yowsup from your phone (wtf), outside a group, to escape the 'No sessions Badmac' limbo:
 This is important, I have only managed to get it working this way. This seems to start axolotl database properly.

Message p2p works, group message works. Sending media files was not tested.

**Comment by Gab0** [comment]
Issue: 
`m.ParseFromString(serializedData) `
@ layers/axolotl/message_receive.py:172 always fail,
raising 
`google.protobuf.message.DecodeError: Truncated message.`

Is protobuf vital for yowsup? It only seem to trim text messages.

**Comment by jlguardi** [comment]
Yes, it is vital. All encrypted media are buffered with this.
It shouldn't be truncated. Could it be a coder issue?

**Comment by Gab0** [comment]
@jlguardi  It may be. But also, when a message is decrypted, the starting byte is '\n' followed by a byte of value equal to the number of characters on the message... If the lenght is greater than 128, this byte will be unable to be decoded to UTF-8. If set decode('utf-8', 'ignore'), the byte will be missing and whatsapp won't accept the message, sending back a retry IQ.
 This is only a issue for outgoing messages, because with incoming messages we can ignore this lenght byte and just cut the message on byte 0x12 which always end a message. Can you help me on this? How to encode a byte bigger than 128 to string?

**Comment by jlguardi** [comment]
I don't have this issue with my master an tgalal/python-axolotl with devel branch. Padding is correctly decoded. 

I've proposed a solution with function v2unpadding (or something simmilar) available in axolotl/layer.py of my master. 

Anyway, I'll try to merge your improvements with my master and feedback.

**Comment by Gab0** [comment]
My fixes are for the reworked wa16, you would have to implement it (skmsg support) on your code first.. I recommend.

**Comment by jlguardi** [comment]
Skmsg are already working on my branches.

**Comment by thundergreen** [comment]
On all branches? I have been  blocked today.yowsup is now dead for me :(

Thorsten Fröhlich
Am 15.04.2016 18:42 schrieb "jlguardi" <notifications@github.com>:

**Comment by jlguardi** [comment]
I've got two branches and the most important is that skmsg is supporte by both. 
A lot of blocked numbers are reported in chatApi. @thundergreen were you using yowsup with transwhat? Do you have auto answers?

**Comment by Gab0** [comment]
Sorry, messed up.. I tested your branch on groups and raised protobuf error (so its obviously implemented but gives error to me) Do you talk to groups normally?

**Comment by thundergreen** [comment]
Yes I use transwhat ... Auto response...nope. I write and receive messages
via yowsup / transwhat script. Now I don't have any number to register on
wa. Project yowsup seems to be dead for me now :( maybe knows a way how to
get an account on wa. Maybe virtual numbers
Any suggestion is welcome ;)
Thorsten Fröhlich
Am 15.04.2016 20:19 schrieb "jlguardi" <notifications@github.com>:

I've got two branches and the most important is that skmsg is supporte by
both.
A lot of blocked numbers are reported in chatApi. @thundergreen
<https://github.com/thundergreen> were you using yowsup with transwhat? Do
you have auto answers?

—
You are receiving this because you were mentioned.

Reply to this email directly or view it on GitHub
<https://github.com/tgalal/yowsup/issues/1499#issuecomment-210574243>
