### ISSUE TITLE
Problem running the bot 

### ISSUE THREAD

**Issue by MauricioAHM** [tgalal/yowsup#1560]
Hi everyone, some one have had this problem with the file run.py?
I don´t find information about how to fix it, 
I would appreciate any help.

![captura de pantalla 54](https://cloud.githubusercontent.com/assets/18564255/14889644/4af11814-0d25-11e6-94e6-44aaf46756e6.png)

**Comment by davidsilveiro** [comment]
Give this a try dude

sudo pip install yowsup2 --upgrade

**Comment by MauricioAHM** [comment]
Hi @davidsilveiro, it works, now the bot is working, but now I have the problem of incomplite messages  issue #1356, and I already did the fix but it doesn´t work

**Comment by k-freeman** [comment]
because you installed via pip, it is no longer dependent on that folder. you should learn some basic unix/python at first and why give yowsup sudo rights? why try to use python commands in shell?

do this:
```
$ cd
$ cd yowsup
$ python2 yowsup-cli (additional parameters)
```
now it is starting in your folder. if you changed files within the yowsup folder, these changes are now working...

**Comment by sowerkoku** [comment]
@MauricioAHM  you must download the bot and get back up

**Comment by jlguardi** [comment]
@MauricioAHM apply the fix and install in the system (sudo python setup.py) or use a non-systemic solution as @k-freeman proposed.
