### ISSUE TITLE
Could not verify existing regitrations

### ISSUE THREAD

**Issue by fafa22** [tgalal/yowsup#1584]
Hello!!!

I'm trying to register my phone with WART and I get the following error "Could not verify existing registration {"status":"fail","reason":"incorrect","sms_length":6,"voice_length":6,"sms_wait":0,"voice_wait":0}

The phone number is 59894XXXXXX. This number is from Uruguay.
I have tried several numbers and all give me the same error.

I could help solve this problem?

![issue](https://cloud.githubusercontent.com/assets/19269095/15118383/55e753d0-15e2-11e6-956a-66933117486b.png)

thank you very much
best regards

**Comment by vsarinho** [comment]
Same here in Brazil. Passwords obtained by WA PW not working too.

**Comment by mgp25** [comment]
@fafa22 you couldnt be more wrong! You are not even requesting the code (sms), if you click in check existing you are doing a request to reset the account's password and if dont have the same identity it wont work! Please read the wiki or something

@vsarinho WA PW works but if you use it with latest .apk it wont let you login, the reason is that when logging in with the .apk you are linking the account with some private and public keys, and in order to log in that are required.

**Comment by vsarinho** [comment]
Sorry, but I didn't explain correctly. My activation process follow these steps:

1) Install WhatsApp in the BlueStack emulator; 
2) Get the password with WA PW; 
3) Remove installed WhatsApp to avoid a conflict; and 
4) Use the password to connect by Yowsup. 

For some reason the 4º step is not working any more. And the attempt to get the password by WART or Yowsup registration process presents the result described by @fafa22.

Last month I lost 2 old phone numbers, but other 2 recent numbers (1-2 months) are connected yet, and now I can't connect new phone numbers.

Any suggestion??

**Comment by thundergreen** [comment]
I face the same Problem :(

Thorsten Fröhlich
Am 11.05.2016 21:31 schrieb "vsarinho" <notifications@github.com>:

**Comment by jlguardi** [comment]
@vsarinho As @mgp25 said, WA PW doesn't work with latest apk.
If you are getting incorrect could be due to local prefix included in some countries. See in official app log file which is the jid used after the registration and use it for yowsup registration. Otherwise, use an older version of wa apk and extract password with WA PW.

**Comment by thundergreen** [comment]
Has someone an old version of wa please ;)

Thorsten Fröhlich
Am 11.05.2016 22:47 schrieb "jlguardi" <notifications@github.com>:

**Comment by vsarinho** [comment]
Solved using ChatAPI registerTool.php .

**Comment by fafa22** [comment]
Thanks for your answers. The answer is the same regardless of the button you press.
I will try to get an earlier version. Regards

**Comment by jlguardi** [comment]
@thundergreen see http://www.apkmirror.com/apk/whatsapp-inc/

I use 2.12.357
