### ISSUE TITLE
Registration: You have to request code first

### ISSUE THREAD

**Issue by MaD-86** [tgalal/yowsup#1647]
I got the code-SMS only by using the extention "-E android", otherwise there was the "no routes" failure.
Now I tried to finish the registration with the code and yowsup gives back this:

Traceback (most recent call last):
  File "yowsup-cli", line 368, in <module>
    if not parser.process():
  File "yowsup-cli", line 191, in process
    self.handleRegister(self.args["register"], config)
  File "yowsup-cli", line 215, in handleRegister
    req = WARegRequest(config["cc"], config["phone"], code)
  File "/home/pi/yowsup/yowsup/registration/regrequest.py", line 35, in __init__
    raise ValueError("You have to request code first")
ValueError: You have to request code first

Any ideas ?

**Comment by jlguardi** [comment]
You need to check:
 - are you using the same pc to send sms and registering? It's mandatory.
 - are you using the same user? The process creates a‎ file in $HOME/.yowsup/phone/Id and it is required for the second step.
 - have you checked if phone number is correctly written? With cc? Both steps require cc and phone with the same format.
 - have you deleted Id file‎?

Otherwise, ‎I don't have an answer but I made all these errors in the past.

**Comment by MaD-86** [comment]
Thanks a lot.
"same user" was the point.
I wrote one with sudo and one without.
