### ISSUE TITLE
Question! what jids actuly is?

### ISSUE THREAD

**Issue by jegue** [tgalal/yowsup#1696]

**Comment by jlguardi** [comment]
The jid is the identifier used by whatsapp for each or group. It use to be cc+phone@s.whatsapp.net for users and cc+phone-timestamp@g.us for groups. 
Some times it differs due to countries with area code. So, check your jid while registering in the returned string and check other users jid with contact info function or you will be banned.

**Comment by jegue** [comment]
@jlguardi thank you!
