### ISSUE TITLE
_USERAGENT_STRING with Android env

### ISSUE THREAD

**Issue by albert-chin** [tgalal/yowsup#1701]
Hello,
The 
_USERAGENT_STRING in  yowsup/env/env.py :
     _USERAGENT_STRING = "WhatsApp/{WHATSAPP_VERSION} {OS_NAME}/{OS_VERSION} Device/{MANUFACTURER}-{DEVICE_NAME}"

With 
    _VERSION = "2.12.556"
    _OS_NAME = "Android"
    _OS_VERSION = "4.3"
    _DEVICE_NAME = "armani"
    _MANUFACTURER = "Xiaomi"
    _BUILD_VERSION = "JLS36C"
in  yowsup/yowsup/env/env_android.py
amounts to
_USERAGENT_STRING = "WhatsApp/2.12.556 Android/4.3 Device/Xiaomi-armani"

But corresponding thing with mgp25/Chat-API, at  Chat-API/src/Constants.php is
WHATSAPP_USER_AGENT = 'WhatsApp/2.16.148 Android/4.3 Device/Xiaomi-HM_1SW'; 

See also "Register fix" there (with mgp25/Chat-API), Commits on Jan 5, 2016 
which fixes something by adding the tailing "-HM-1SW"

Any update needed in yowsup/env/env.py  ??

Regards.

**Comment by jlguardi** [comment]
Since some time ago, Device is defined as device_manufacturer (manufacturer) and device_name (model codename). Both should exist and Xiaomi-armani is a valid string.

However, if you prefer, you can replace it by any valid pair. Check also about valid kernel build version, which is used for initial password hashing.

**Comment by albert-chin** [comment]
Thanks
