### ISSUE TITLE
Axolotl layer does not have the message

### ISSUE THREAD

**Issue by Domeax** [tgalal/yowsup#1730]
DEBUG:yowsup.layers.axolotl.layer_send:Axolotl layer does not have the message, bubbling it upwards

I get this message while my bot is receiving a message from me.
The bot is working for around 5 minutes, but after this period of time the connection is closed.

Is there any solution i can fix this error?

**Comment by jlguardi** [comment]
This message is due to after yowsup restart, all previously sent messages are forgotten. So the incoming ack doesn't match any message. However, it isn't an error but a debug message.

If your instance dies every 5 minutes, it's due by other reason (usually, last debug message says the cause). Please, post full log (or, at least, the latest log lines).
