### ISSUE TITLE
Sharing a link causes 'utf8' codec can't decode byte 0xff in position 0 

### ISSUE THREAD

**Issue by ghost** [tgalal/yowsup#1775]
The following error occurs when sharing a link with embedded image metadata such as https://nl.wikipedia.org/wiki/JPEG

`File "C:\messenger\lib\site-packages\google\protobuf\internal\decoder.py", line 469, in _ConvertToUnicode
    return local_unicode(byte_str, 'utf-8')
UnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 0: 'utf8' codec can't decode byte 0xff in position 0: invalid start byte in field: com.whatsapp.proto.UrlMessage.jpeg_thumbnail
`

Duplicate of #1591

**Comment by rodrigolopezguerra** [comment]
Hi , i'm confused. If this is a duplicated why the report? In the other hand , if is really the case you have the solution wright there "@bzero this is a bug layers/protocol_messages/proto/wa.proto jpeg_thumbnail should be bytes instead of string. You need to regenerate wa_pb2.py o edit it manually.
You can also use the wa_pb2.py in my master which h some other fixes.". and if not , pleae share your code in order to check if someone can help you. Regards!

**Comment by epdittmer** [comment]
Hi, I found the duplicate after filing the report. The fix proposed in #1591 was not marked as fully functional (e.a. it resolved the error but does not function as expected). Will try to add the fix shorty.

**Comment by AragurDEV** [comment]
I tried fixing it on my version. But I didn't get it working.
@rodrigolopezguerra I tried your attempt with the help of @jlguardi 's repository but nothing worked at all after i pulled his wa.proto and wa_pb2.py
I'm using Python 3 and Protobuf was yelling to me with an NotImplementError

**Comment by rodrigolopezguerra** [comment]
Not using python 3 here. Not sure if related Worked for me.

**Comment by AragurDEV** [comment]
Is Python 3 realy the problem?

**Comment by tgalal** [comment]
0acd4400e35cf7921def5162a92fcd5d0f64b806
