### ISSUE TITLE
How to upload image & send?

### ISSUE THREAD

**Issue by Wiku5** [tgalal/yowsup#178]
What is the way to upload an image?

I understand how to send it, but I need to be able to send the URL that is located on WhatsApp's server.

Is there any documentation to send via Uploader.py under media? For the life of me, i can't get it to work regardless of any workarounds.

Many thanks!

**Comment by awesomebytes** [comment]
Same here, the image is not delivered.

**Comment by nautical** [comment]
Its working now

**Comment by awesomebytes** [comment]
Did you make any change @nautical? Because it's not working for me. In this Issue it's said it's legacy and it's not being fixed it seems https://github.com/tgalal/yowsup/issues/413

Then another issue was opened here: https://github.com/tgalal/yowsup/issues/581
Which has some explanation (which I'll try to use now) but does not seem to be resolved.
