### ISSUE TITLE
Retrieving mesage history

### ISSUE THREAD

**Issue by steckerhalter** [tgalal/yowsup#1809]
Does yowsup currently support retrieving old messages in any way? If yes could you point to the Python methods that would have to be used for this purpose?

I especially would like to be able to get the history from a group chat.

**Comment by jlguardi** [comment]
No, it isn't supported. This info isn't stored in wa servers but you could recover it with google account backup but it isn't implemented.

**Comment by steckerhalter** [comment]
Thanks, weird I must say. They don't save any history? It's hard to believe :)

**Comment by jlguardi** [comment]
Whatsapp can't store history due to all messages are encrypted end to end. So they can't access to message content.
History can be stored into you google account by your app (not by server) but you need to enable this feature in your mobile.
Anyway, as I said, this feature‎ isn't implemented by yowsup.

**Comment by steckerhalter** [comment]
Ok, thanks for explaining.

**Comment by alexpirine** [comment]
Hello… Sorry to bug again, but why the official web or desktop client can retrieve the history, without any google account?
