### ISSUE TITLE
ValueError: You have to request code first

### ISSUE THREAD

**Issue by elidrissizack** [tgalal/yowsup#1897]
sudo yowsup-cli --register 296961 --phone 212XXXXX --cc 212 
Available commands:
===================
demos, version, registration

thanks for ur help

**Comment by mgp25** [comment]
@elidrissizack exactly what the error says. You have to request a code (sms oir voice code) in order to register with that given code.

Keep in mind that if you have previously requestes it has an expiration time, so once expired, you need to request one again.

I think this is explained in the wiki or other issues

Regards

**Comment by elidrissizack** [comment]
thanks solved
