### ISSUE TITLE
Loop

### ISSUE THREAD

**Issue by juanicotolengo** [tgalal/yowsup#2004]
Hi all!! I'm trying to execute an action when yowsup loops. By now, let's take it as something silly: how can I print a message everytime that yowstack loops? I'm sorry if it's a foolish question, new to python, and can't figured it out!

**Comment by juanicotolengo** [comment]
BTW: I'm using the echo client example.

**Comment by AragurDEV** [comment]
The stack loop is "extreamly" fast loop, which is for recieving messages only.
You have to start a second thread with a loop to execute looped actions.

**Comment by juanicotolengo** [comment]
By fooling around, find out that every minute or so, the method send, that belongs to the class YowStanzaRegulator, gets called. That's where I'm going to do my stuff. Perhaps is not the best, but I'm not that experienced in Python to create threads (although I'm going to learn in a future about that). Thanks!

**Comment by CantuOSS** [comment]
@juanicotolengo check the asyncore documentation, since yowsup implementation uses it for its lifecycle and communication, you could set a max number of connections and a timeout so you can call the loop start, listen for a finite number of events with a defined timeout, and then the loop will end, so you can implement an infinite loop that does the loop and pass some parameters to the class so you can use new information once it ends. I'll share some of my code later for better understanding
