### ISSUE TITLE
Connection always closed after ~20 minutes

### ISSUE THREAD

**Issue by munknex** [tgalal/yowsup#2021]
Attached [full typical log](https://vkdog.tk/avatars/out.log.zip).

In short:
```2017-05-02 20:13:05,192 Env not set, setting it to s40
2017-05-02 20:13:05,193 Current env changed to s40 
2017-05-02 20:13:05,193 Initializing stack
2017-05-02 20:13:05,193 Constructed Network Layer
2017-05-02 20:13:05,193 Constructed Stanza Regulator Layer
2017-05-02 20:13:05,193 Constructed Crypt Layer
2017-05-02 20:13:05,194 Constructed Coder Layer
2017-05-02 20:13:05,194 Constructed Logger Layer
2017-05-02 20:13:05,194 Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
2017-05-02 20:13:05,196 Constructed Interface Layer
2017-05-02 20:13:05,196 started client

...
<iq xmlns="urn:xmpp:whatsapp:sync" type="get" id="1">
    <sync index="0" last="true" mode="full" context="interactive" sid="...">
        <user>...</user>
        ...
    </sync>
</iq>


<iq type="result" from="...@s.whatsapp.net" id="1">
    <sync>
        <in>
            <user>...</user>
            ...
        </in>
    </sync>
</iq>

...
# subscribing to all contacts
<presence to=“...@s.whatsapp.net" type="subscribe"></presence>

#getting presence updates
...

2017-05-02 20:33:05,975 Disconnected, reason: Connection Closed
2017-05-02 20:33:06,481 stopping ping thread
```

**Comment by munknex** [comment]
@CantuOSS please, take a look

**Comment by CantuOSS** [comment]
@munknex seems to me that the order you are doing your requests is wrong, and that may be why you are getting disconnected, please elaborate on your implementation (stack and layer). Are you using one of the examples?

**Comment by munknex** [comment]
@CantuOSS 

[entire code is here](http://vkdog.tk/avatars/wa_check.py)

**Comment by munknex** [comment]
Actually, I've just checked. It disconnects even if you only login and wait. Looks like WhatsApp changed it's behaviour. Any ideas how to workaround it?

**Comment by CantuOSS** [comment]
i'm seeing many potential situations that could cause that behaivor. I see you are sort of using the cli example as baseline and removed a bunch of stuff out of it. 

In line 135:
`stack.loop(timeout = 0.5, discrete = 0.5)`
the timeout parameter is telling asyncore that it only has half a second to wait for incoming connections, you should increase that number so it waits more time for connections (the default i think is 3).

Lines 103-114:
```
    @ProtocolEntityCallback("success")
    def onSuccess(self, entity):
        self.connected = True
        log.debug("Logged in!")
        self.presence_available()
        time.sleep(2)

        def on_got_contacts(res, originalIqProtocolEntity):
            for phone, jid in res.inNumbers.iteritems():
                self.presence_subscribe(jid)

        self.sync_phones(PHONES, on_got_contacts)
```

Don't call `time.sleep(2)` since the execution is async and that could break the loop or at least make it behave unnexpectedly, besides it has no purpose being there.
You are placing `def on_got_contacts(res, originalIqProtocolEntity):` inside `def onSuccess(self, entity):`. I see no purpose for that having that identation.

In lines 94-97:
```
    @ProtocolEntityCallback("iq")
    def onIq(self, entity):
        self.last_iq_at = time.time()
        log.debug("[iq] {}".format(int(self.last_iq_at - self.app_start_at)))
```

If you are implementing your own iq entitycallback, you need to see how to send iq to whatsapp server so it knows you are alive. I may be wrong about this, you should check the examples for clarification.
