### ISSUE TITLE
Try to send - no errors but I receive nothing

### ISSUE THREAD

**Issue by hssergey** [tgalal/yowsup#2105]
I have successfully registered using settings as https://github.com/tgalal/yowsup/issues/2090#issuecomment-305580100

But when I try to send message using cli demo:

yowsup-cli demos -l my_phone:my_password -s my_another_phone testtesttest

the app finish without errors but I receive nothing.

yowsup-cli  v2.0.15
yowsup      v2.5.2

**Comment by schlaubstar** [comment]
Take a look at #2093 - Seems to be a common problem - Some say that it might be the end of support of wa-protocol v1.6 - others say you need to update the android-version number and the MD5-Code. 
I don't know because I just downloaded and installed it and I don't know if it would have been working a week ago, or not.

**Comment by xwanyiri** [comment]
Had the same problem. The app finished without an error and the message was not received. I tried it on another computer with a freshly installed yowsup and it worked fine

**Comment by jlguardi** [comment]
It could by:
 - incorrect nonce file so login fails. solution remove .yowsup/phone/nonce. It has no problem due to nonce is recomputed if removed. 
- axolotl.db has an incorrect entry for this recipient. This is usual if you run yowsup in other computer. You can remove the axolotl.db file but you coul loss some other incomming messages. 
Anyway, execute cli app in debug mode ans try to send a message to this recipient. (yowsup-cli demos -y -d ...). Then post logs.

**Comment by schlaubstar** [comment]
@jlguardi  Thanks for your feedback. As I don't mind losing messages I have deleted nonce and axolotl.db 
I also checked the russian scratch-site and updated version and MD5_hash for android.
On the first call it will recalculate some keys and regenerate nonce. 

The second try:

Forced to be an S40:
`> python yowsup-cli demos -c yowsup-conf -s xxxxxxxxxx  "Test" -d -E s40
DEBUG:yowsup.env.env:Current env changed to s40
yowsup-cli  v2.0.15
yowsup      v2.5.2

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed <yowsup.layers.axolotl.layer_control.AxolotlControlLayer object at 0x76260a50>
DEBUG:yowsup.stacks.yowstack:Constructed Axolotl Layer - <yowsup.layers.axolotl.layer_receive.AxolotlReceivelayer object at 0x762606d0>
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
DEBUG:yowsup.stacks.yowstack:Constructed Interface Layer
DEBUG:yowsup.layers.network.layer:Connecting to e6.whatsapp.net:443
DEBUG:yowsup.layers.logger.layer:tx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="true" user="xxxxxxxxxx" mechanism="WAUTH-2">
        n}▒j▒Y▒>▒+▒▒t.ڇ7▒Y*▒▒H▒{▒▒▒J
                                    ▒▒▒'▒▒:▒▒▒Ğ'▒](▒▒▒▒
                                                       NQ5PB3▒=▒▒'▒
HEX:096e7d12dd6ac859e23ead2bbefa742eda8737c9592afbf848987b8da2dd4a0b0193b69d27d2e63abbeed4c49e0f27a65d289596a9fb0b4e513514501f4233e43dbdbf27f101
</auth>

DEBUG:yowsup.layers.logger.layer:rx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:rx:
<success status="active" kind="free" creation="1495397943" expiration="4444444444" props="15" t="1497214198">
▒*
 ▒▒h▒▒AX=▒QC▒▒
HEX:c52a080bfeca1168a5f39c41583d14f55143b5df
</success>

DEBUG:yowsup.layers.protocol_iq.layer:starting ping thread.
DEBUG:yowsup.layers.logger.layer:tx:
<message to="yyyyyyyyyyyyyy@s.whatsapp.net" type="text" id="1497214198-1">
<enc type="pkmsg" v="2">
▒▒▒!▒▒▒T8▒KB▒Ur▒▒K.;▒2▒ 7▒"▒0▒▒={!▒▒E▒n#▒Ei;5m▒▒g▒T▒tg▒>▒|▒K~^"▒3
!H▒▒2▒-▒m
▒▒▒W▒▒
      ▒▒▒▒▒I▒i▒I'"▒▒0▒p▒O▒!▒m▒5▒▒▒~R▒]Cc▒▒>▒4Z▒t▒▒▒܌▒D▒j▒c▒▒M▒▒▒Tz}s*▒▒▒ٌ▒▒#s▒h▒p8ע▒qG@▒▒U▒3c\▒7▒pV"▒▒(▒▒▒▒▒▒s[D▒6,▒▒@▒FbV▒▒▒v}&j▒▒▒";pD▒b▒▒|P
▒▒\     ▒
!▒▒▒u▒qv▒▒▒▒▒Pj2▒kȧQ:H(▒▒▒▒0

HEX:330890bbe0011221058db5e5a95438954b42a75572c606dd4b1c2e3b8232c10937c622de30f7c03d7b1a21058a8e45bf056e238545693b350e6da19a67af54c87467a23e887cf94b17037e5e22e301330a210548afd032812dba6d0c979b86578a149a060e0bb992ced505eca2498769ee49271001180022b0010596308a7095777f4f9e21ad6dfa35b813160501f5f9af7e52b7055dc97f436389823e85345abc741786859adc8cbd44fd6a8163bbdc124d9cc4db547a7d732a8eea0e88d98ce5f1892373b90168a47038d7a2d3714740eae655d5331bd2635c8237e7705622e11b62ad2892e4d2f2018386735b44f6362c97f44095466256e4d1f4767d266a88e5a410e6223b70449562ffcc7c500c92ab5c099a190a21e9e518b375a07176a29c81d8d11f506a3210896bc8a7513a481f2899a399950e300c
</enc>
</message>

PuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYDEBUG:yowsup.layers.logger.layer:rx:
<ib from="s.whatsapp.net">
<dirty timestamp="1497214198" type="groups">
</dirty>
</ib>

DEBUG:yowsup.layers.logger.layer:rx:
<ack t="1497214198" from="yyyyyyyyyyyyyy@s.whatsapp.net" class="message" id="1497214198-1">
</ack>

INFO:yowsup.demos.sendclient.layer:Message sent

Yowsdown`

Same command without specifying -E S40 (which basically means: android)

`python yowsup-cli demos -c yowsup-conf -s yyyyyyyy "Test" -d
yowsup-cli  v2.0.15
yowsup      v2.5.2

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


DEBUG:yowsup.env.env:Env not set, setting it to android
DEBUG:yowsup.env.env:Current env changed to android
DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed <yowsup.layers.axolotl.layer_control.AxolotlControlLayer object at 0x7625ba30>
DEBUG:yowsup.stacks.yowstack:Constructed Axolotl Layer - <yowsup.layers.axolotl.layer_receive.AxolotlReceivelayer object at 0x7625b6b0>
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
DEBUG:yowsup.stacks.yowstack:Constructed Interface Layer
DEBUG:yowsup.layers.network.layer:Connecting to e2.whatsapp.net:443
DEBUG:yowsup.layers.logger.layer:tx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="true" user="xxxxxxxxxxxx" mechanism="WAUTH-2">
"▒▒Ȩ@/z▒8▒▒G@x▒7▒▒▒Kx▒▒%E▒▒▒\B▒▒+Mٌ
HEX:274a3567314ed0ff08e69a81092e9f873c7e72d29223cb7321993701320d22028c92c8a8401d2f7a0f9238eed28308b987474078fd3790a2964b78bf17f32545a306cec15c4203bfee962b4dd98c
</auth>

DEBUG:yowsup.layers.logger.layer:rx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:rx:
<challenge>
▒yA\▒N▒[▒n▒cp▒+▒z▒
HEX:e679415cb24e039c5ba16e8b6370e82b9f7aee01
</challenge>

DEBUG:yowsup.layers.logger.layer:tx:
<response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">
▒u6▒▒▒{?▒~▒l▒▒▒▒▒N50▒P▒▒m▒"S▒E4W▒:ˋ▒B▒▒fړ▒▒ʂ▒?▒▒B▒▒▒    ▒▒5 ▒▒▒nRT
HEX:c47536adb88d7b3fd71f7ea36cdbede7d717bf4e3530f550a301876dc02253e3451034579c3acb8bfd1642f3aee46613da93c30fb916ca82f39f3ffbf542b5a8a709d4ca3520a696ec1bdd6e5254
</response>

DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed`

Obviously it seems to do something different after the attemp to authentificate .... but why?

**Comment by jlguardi** [comment]
S40 can login due to it uses wa1.6 protocol. However, android uses wa2.0 which isn't implemented. So server rejects the connection.

**Comment by hgc2002** [comment]
This issue is happening to me. I can send, no errors, but nothing is received in the destination phone.
please advice.

my environment is windows7 64 bits, python 3.3.5 and yowsup 2.5.2. 
everything compiled/installed fine, including axolotl and pcrypto.

this is what I did before the test:
.- I've updated MD5 recently
.- The source phone was registered correctly (with the new MD5)
.- The axolotl.db and rest of files were deleted (folder was cleared completely)
.- I've set s40 as default. With Android it doesn't work (maybe because WA2.0)

this is how it was run (send.bat), directly from CMD at yowsup master folder:
@echo off
set source=--hidden--
set pass=--hidden--
set destination=--hidden--
set message="this is the test message 01"
set options=--debug -l %source%:%pass% -M -E %env% --send %destination% %message%
python yowsup-cli demos %options% > output.txt 2>&1

now, here is the output with --debug:

DEBUG:yowsup.env.env:Current env changed to s40 
DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
DEBUG:yowsup.stacks.yowstack:Constructed Interface Layer
DEBUG:yowsup.layers.network.layer:Connecting to e15.whatsapp.net:443
DEBUG:yowsup.layers.logger.layer:tx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:tx:
<auth mechanism="WAUTH-2" passive="true" user="--hidden--">
</auth>

DEBUG:yowsup.layers.logger.layer:rx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:rx:
<challenge>
å\x9cøY[µ\x90ê wLRd\x8eø(5f1µ
HEX3:b'e59cf8595bb590ea20774c52648ef828356631b5'
</challenge>

DEBUG:yowsup.layers.logger.layer:tx:
<response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">
uÍgH9\x88WC\x9crÊ2Ñ\x97Êîz"¯ê5ÍfÅ«Å$TËÑ\x98¶j\x94fhìÚ6\x89gJ»÷ò]ClRèþ£M32EÔu\x8a\x9e
HEX3:b'75cd6748111e398857439c72ca32d197ca0cee7a22afea35cd66c5abc504241c54cb17d1980eb66a940c6668ecda360b89674abbf7f25d436c52e8fea34d333245d4758a9e'
</response>

DEBUG:yowsup.layers.logger.layer:rx:
<success kind="free" status="active" props="16" t="1503908326" creation="1503606688" expiration="4444444444">
7b0èä&Bmþ$I«jqU&w
HEX3:b'0b376230e80ee426426dfe2449ab1c6a71552677'
</success>

DEBUG:yowsup.layers.protocol_iq.layer:starting ping thread.
DEBUG:yowsup.layers.logger.layer:tx:
<message id="1503908326-1" to="--hidden--@s.whatsapp.net" type="text">
<body>
this is the test message 01
HEX3:b'6573746520657320656c206d656e73616a65203031'
</body>
</message>

DEBUG:yowsup.layers.logger.layer:rx:
<ib from="s.whatsapp.net">
<dirty timestamp="1503908326" type="groups">
</dirty>
</ib>

DEBUG:yowsup.layers.logger.layer:rx:
<ack t="1503908326" from="--hidden--@s.whatsapp.net" id="1503908326-1" class="message">
</ack>

INFO:yowsup.demos.sendclient.layer:Message sent
yowsup-cli  v2.0.15
yowsup      v2.5.2

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate



Yowsdown

--end of output--

**Comment by hgc2002** [comment]
solved, I think.
I run yowsup-cli in command line mode and all the axolotl keys for my phone were loaded (the axolotl.db got created finally) and the /message send command worked pretty fine.

Then, the batch script run perfectly.

**Comment by fjrmaulana** [comment]
Did you register twice and then the database from android you move to home / user?
