### ISSUE TITLE
old_version i cant fix help me

### ISSUE THREAD

**Issue by endermrn2** [tgalal/yowsup#2175]
root@endermrncontrol:~# yowsup-cli registration --requestcode call --phone 34632418013      --cc 34 --mcc 214 --mnc 25
yowsup-cli  v2.0.15
yowsup      v2.5.2

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

INFO:yowsup.common.http.warequest:{"login":"34632418013","status":"fail","reason":"old     _version"}

status: fail
reason: old_version
login: 34632418013

**Comment by Morr1s** [comment]
I have the same Problem. It seems that we need to edit the variables  _VERSION and _MD5_CLASSES in yowsup/env/env_android.py. I read that you can get it from https://coderus.openrepos.net/whitesoft/whatsapp_scratch, but I used the newest one and it didn't work for me. Does anybody see what I did wrong?
I used:
_MD5_CLASSES = "3jYxFPSrhqjabEm5b2sXhA=="
 _VERSION = "2.17.279"
Is there a way of fix this problem?

Thank you a lot for your help!

**Comment by endermrn2** [comment]
thanx you very much

**Comment by endermrn2** [comment]
_MD5_CLASSES = "3jYxFPSrhqjabEm5b2sXhA=="
_VERSION = "2.17.279" this work

**Comment by sealabr** [comment]
this fixed thanks!

**Comment by pablosharper** [comment]
Can Anyone send me the md5 classes for 2.17.282 please?

**Comment by Morr1s** [comment]
did you tried it with my md5 class and version. Did you tried it executing with ./ ?

**Comment by strafun** [comment]
Hello also cant register number already with your md5 and version. my code: 
`python ./yowsup-cli registration --requestcode voice --phone 6***** --cc 62`

**Comment by Morr1s** [comment]
try with adding -E Android

**Comment by strafun** [comment]
tried - same result. any Ideas? for you it is works now?

**Comment by Morr1s** [comment]
Yes for me it is working. Sorry but I don't have any further suggestions.

**Comment by sealabr** [comment]
I made a prototype for md5 class extractor: test this for me please:

md5class = xZtxciKuI7Gzv2i2XIsyWQ==
version: 2.17.283

**Comment by strafun** [comment]
@sealabr nope - but i hope in my way reason is diff - will try tomorrow on server

**Comment by kasikcz** [comment]
md5class = "ETAnhWrz/tGEeDZScjEyIA=="
version: 2.17.285  //beta 
and did not work for me :/
last release is 2.17.254

**Comment by alexcarpenedo** [comment]
I've already tested all the ways above and the problem still remains...



E 2021-06-23 18:40:37,472 yowsup.config.manager - Could not find a config for username=CC----------, paths checked: /home/servidor/.config/yowsup/CC----------/config.yo:/home/servidor/.config/yowsup/CC----------/config.json
yowsup-cli  v3.2.0
yowsup      v3.2.3

Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


I 2021-06-23 18:40:38,073 yowsup.common.http.warequest - b'{"login":"CC----------","status":"fail","reason":"old_version"}\n'
status: b'fail'
reason: b'old_version'
login: b'CC----------'

**Comment by sealabr** [comment]
this not work anymore!!! give up!!!!!!!!!!!!!!!!!!

**Comment by ben221199** [comment]
**To make clear:** `old_version` only happens when the `token` parameter is missing or invalid during registration.

On Android, it is based on the following items:
 - The certificate of the APK
 - A MD5 calculation of `classes.dex` inside the APK
 - A secret key (calculated by hashing `about_logo.png` and some other things, but it is actually constant over time)
 - The User-Agent, which is sent in the HTTP header

The certificate and secret key don't change over time, but the MD5 calculation and the User-Agent are version dependent.
For example, version `2.20.206.22` does have `oEYGYTr+K6IN0mDOrAZpsg==` as MD5 calculation. This are the only two you have to change every time.

If changing this does not work, it is possible that the token-generator function is broken or the user-agent is not sent or invalid.
Here is a working token-generator function: https://github.com/ben221199/WAPI/blob/java/src/main/java/nl/ben221199/wapi/Verification.java
To make sure you have a valid User-Agent, look here:
https://github.com/ben221199/WAPI/blob/java/src/main/java/nl/ben221199/wapi/Constants.java
