### ISSUE TITLE
media message not download

### ISSUE THREAD

**Issue by manojrao** [tgalal/yowsup#2185]
Hello yowsup developers i received text message properly but media message not save in my panel proper. how to download media message in my system. please guide me.

**Comment by vteccomm** [comment]
same issue plz update if any progress

**Comment by jakibaki** [comment]
Media downloading is currently broken in the normal yowsup due to images being encrypted by default. You can use [my fork](https://github.com/jakibaki/yowsup) (basically just normal yowsup with the fix by @jbollacke which adds download and decryption of media).

Just call `message.getMediaContent()` and it will return the decrypted media as an byte-array.

**Comment by vteccomm** [comment]
really appreciate your reply 
i m sorry i am newbie here 
r u suggesting me to del all previous work and start over again ?
and i didn't understand where i will call this function **message.getMediaContent()** 
into yowsup-cli ?
thanks

**Comment by jakibaki** [comment]
yowsup-cli doesn't have this feature implemented right now, I assumed that you were going to write an bot using the normal api.

If you want that feature in yowsup-cli you can implement it yourself though.

Take a look at `onMessage(self, message)` in `yowsup/demos/cli/layer.py`, it's whats called whenever yowsup-cli gets an message. You can implement downloading the image wherever you want it there.

**Comment by marcosnils** [comment]
@jakibaki it's amazing that you took the time to fix the media decryption. Is there a PR in place so the changes can be merged in the upstream repo?

**Comment by tgalal** [comment]
See [media sink](https://github.com/tgalal/yowsup/blob/master/yowsup/demos/mediasink/layer.py) demo
