### ISSUE TITLE
No communication with the instrument (no answer)  Minimal modbus

### ISSUE THREAD

**Issue by arsohel** [tgalal/yowsup#2187]
hi, i want to connect my RPI to schneyder pm1200 through usb to rs485 communication. my code is below. Baud rate, parity, bytesize slave address and register addess as per schneider please anyone help me

import minimalmodbus
import serial
instrument = minimalmodbus.Instrument('/dev/ttyUSB0', 1)
instrument.serial.port          # this is the serial port name
instrument.serial.baudrate = 9600   # Baud
instrument.serial.bytesize = 8
instrument.serial.parity   = serial.PARITY_EVEN
instrument.serial.stopbits = 1
instrument.serial.timeout  = 0.05   # seconds

#instrument.address   # this is the slave address number
instrument.mode = minimalmodbus.MODE_RTU   # rtu or ascii mode
print instrument
voltage = instrument.read_register(3911, 2) # Registernumber, number of decimals
print voltage

output::::
>>> 
minimalmodbus.Instrument<id=0x7571c418, address=1, mode=rtu, close_port_after_each_call=False, precalculate_read_size=True, debug=False, serial=Serial<id=0x7574bd30, open=True>(port='/dev/ttyUSB0', baudrate=9600, bytesize=8, parity='E', stopbits=1, timeout=0.05, xonxoff=False, rtscts=False, dsrdtr=False)>

Traceback (most recent call last):
  File "/home/pi/Schneider_3.py", line 14, in <module>
    voltage = instrument.read_register(3911, 2) # Registernumber, number of decimals
  File "/usr/local/lib/python2.7/dist-packages/minimalmodbus.py", line 258, in read_register
    return self._genericCommand(functioncode, registeraddress, numberOfDecimals=numberOfDecimals, signed=signed)
  File "/usr/local/lib/python2.7/dist-packages/minimalmodbus.py", line 697, in _genericCommand
    payloadFromSlave = self._performCommand(functioncode, payloadToSlave)
  File "/usr/local/lib/python2.7/dist-packages/minimalmodbus.py", line 795, in _performCommand
    response = self._communicate(request, number_of_bytes_to_read)
  File "/usr/local/lib/python2.7/dist-packages/minimalmodbus.py", line 930, in _communicate
    raise IOError('No communication with the instrument (no answer)')
IOError: No communication with the instrument (no answer)
>>>

**Comment by sealabr** [comment]
I think you are in wrong repository project.

**Comment by embedded92** [comment]
I'm stuck with similar problem"No communication with the instrument (no answer) Minimal modbus". Somebody please help!!

**Comment by EasyWinCode** [comment]
Somebody please help!!)

**Comment by EasyWinCode** [comment]
instrument = minimalmodbus.Instrument("COM6", 1)  # port name, slave address (in decimal)
#instrument.serial.port                     # this is the serial port name
instrument.serial.baudrate = 9600         # Baud
instrument.serial.bytesize = 8
instrument.serial.parity   = serial.PARITY_NONE
instrument.serial.stopbits = 1
instrument.serial.timeout  = 1         # seconds

#instrument.address                         # this is the slave address number
instrument.mode = minimalmodbus.MODE_RTU   # rtu or ascii mode
instrument.clear_buffers_before_each_transaction = True
-------------------------------------------------------------------------------------------------------------
Modbus Poll working good with the parametrs? butthe library is not working....

**Comment by EasyWinCode** [comment]
minimalmodbus.Instrument<id=0x2241fa32cd0, address=1, mode=rtu, close_port_after_each_call=False, precalculate_read_size=True, clear_buffers_before_each_transaction=True, handle_local_echo=False, debug=True, serial=Serial<id=0x2241fb52220, open=True>(port='COM6', baudrate=9600, bytesize=8, parity='N', stopbits=1, timeout=0.2, xonxoff=False, rtscts=False, dsrdtr=False)>
MinimalModbus debug mode. Will write to instrument (expecting 7 bytes back): '\x01\x03\x9cB\x00\x01\nN' (01 03 9C 42 00 01 0A 4E)
MinimalModbus debug mode. Clearing serial buffers for port COM6
MinimalModbus debug mode. No sleep required before write. Time since previous read: 122394921.00 ms, minimum silent period: 4.01 ms.
MinimalModbus debug mode. Response from instrument: '' () (0 bytes), roundtrip time: 204.0 ms. Timeout for reading: 200.0 ms.

Failed to read from instrument
MinimalModbus debug mode. Will write to instrument (expecting 7 bytes back): '\x01\x03\x9cL\x00\x01k\x8d' (01 03 9C 4C 00 01 6B 8D)
MinimalModbus debug mode. Clearing serial buffers for port COM6
MinimalModbus debug mode. Sleeping 4.01 ms before sending. Minimum silent period: 4.01 ms, time since read: 0.00 ms.
Traceback (most recent call last):
MinimalModbus debug mode. Response from instrument: '' () (0 bytes), roundtrip time: 218.0 ms. Timeout for reading: 200.0 ms.
  File "C:/Users/donda/PycharmProjects/P_mb_ard/MinimalModbus.py", line 36, in <module>
    temperature = instrument.read_register(40012, 0)  # Registernumber, number of decimals

  File "C:\Users\donda\AppData\Local\Programs\Python\Python38\lib\site-packages\minimalmodbus.py", line 441, in read_register
    return self._generic_command(
  File "C:\Users\donda\AppData\Local\Programs\Python\Python38\lib\site-packages\minimalmodbus.py", line 1170, in _generic_command
    payload_from_slave = self._perform_command(functioncode, payload_to_slave)
  File "C:\Users\donda\AppData\Local\Programs\Python\Python38\lib\site-packages\minimalmodbus.py", line 1240, in _perform_command
    response = self._communicate(request, number_of_bytes_to_read)
  File "C:\Users\donda\AppData\Local\Programs\Python\Python38\lib\site-packages\minimalmodbus.py", line 1406, in _communicate
    raise NoResponseError("No communication with the instrument (no answer)")
minimalmodbus.NoResponseError: No communication with the instrument (no answer)
