### ISSUE TITLE
Why is my number getting banned by whatsapp

### ISSUE THREAD

**Issue by himanshushakya** [tgalal/yowsup#2198]
Hi @tgalal ,

I have been trying to register my number in whatsapp but after sometime it gets banned and starts throwing unauthorized error.
Is there a way to prevent our number to get banned?

Thanks

**Comment by himanshushakya** [comment]
I am getting this error:
general: Login Failed, reason: not-authorized
DEBUG:yowsup.layers.network.layer:Disconnected, reason: Authentication Failure
Auth Error, reason not-authorized

**Comment by mcubillos** [comment]
Can you solved this? I have the same error and also when I try to register my number again it shows a error cause 'blocked'

**Comment by himanshushakya** [comment]
Not yet.
Still struggling to find a solution

**Comment by HumGuz** [comment]
i have the same problem, i have been banned 2 times with 2 diferents numbers in less of 6 days

**Comment by himanshushakya** [comment]
@HumGuz @mcubillos can you please share your pattern, like- how you register your number(with env) and what you did before your numbers got banned?
This way we can figure out the pattern used by whatsapp to ban numbers
thanks

**Comment by HumGuz** [comment]
@himanshushakya thanks for the help,  i use yowsup for send notifications about gps tracking, i dont read answers from my users, and there is only text on the messages:
this is the command for register:

> python  yowsup-cli registration --requestcode sms --phone 5214490000000 --cc 521 --mcc 334 --mnc 020 -env android

then, whatsapp send me the code and i confirm it using:

> python  yowsup-cli registration --register 605500 --phone 521440000000 --cc 521

i got the password successfully, i put in the config file the password and the phone and tested  the service using a sample message:

> yowsup-cli demos --config yowsup-cli.config --send 52144900000 'Tenemos Whatsapp'

at this point everything work fine, then i set up my service, its a simple script that get info from a mysql database, and use os.system to ejecute the send message command

> cadena="python yowsup-cli demos --config yowsup-cli.config --send %s '%s'"% (numero, mensaje)
              os.system(cadena)
it works by 3 or 4 days and after that time, its banned, i have 2 more scripts running in this way since last March and still working fine, but i need a third one and got this problem, since i register the other 2 numbers, tha command for register and the version in env_40 changed, i think this can be the problem, when i send a request to whatsapp support, they tell me that its not allowed to use the same number in two diferent devises, hope you can help me

thanks!!!

**Comment by cygni69** [comment]
I think that you should use always "-env android" in every call after registration (the default is S40 if I'm not wrong).
Otherwise WA belives that you are using different devices simultaneously...

Please report success or not...
regards!

**Comment by tgalal** [comment]
https://github.com/tgalal/yowsup/wiki/FAQ#how-do-i-prevent-banning-of-my-account
