### ISSUE TITLE
Dear Tgalal

### ISSUE THREAD

**Issue by Alellandrou** [tgalal/yowsup#2412]
Dear Tgalal, if you think that my issues are irrelevant ok, but why yo dont close too this issue #2408, or this #2380 or this #2377 or this #2383 :v 

@protocolentitycallback("message")

if i write more than one appears the next error: Traceback (most recent call last):

File "run.py", line 2, in 
from layer import EchoLayer

IndentationError: unexpecte indent

**Comment by mgp25** [comment]
Hello @Alellandrou, 

Do you know what `IndentationError`? That's the first thing you should search, not in here but in google. After searching it, you will realize that you are doing something wrong and it is not API fault. This is why your issues are getting closed, because they are `not related`.

You should differenciate between errors in your code and issues in the API.

And what @tgalal is doing is okay. I would also close the issue if its `not related`.

Regards
