### ISSUE TITLE
ERROR:yowsup.layers.interface.interface:Stream Error type: ack {'ack': None}

### ISSUE THREAD

**Issue by dgazotto** [tgalal/yowsup#2525]
I'm not able to receive messages and it's appearing these debug messages:

WARNING:yowsup.layers.axolotl.layer_receive:InvalidMessage or InvalidKeyIdException for XXXX, going to send a retry
INFO:yowsup.layers.axolotl.layer_receive:Trying GetKeys for XXXX, getting keys now

ERROR:yowsup.layers.interface.interface:Stream Error type: ack
{'ack': None}

I already removed the .yowsup directory but still cannot receive. Any ideas? :(

**Comment by j-gkr** [comment]
Same issue here!

Did you get a solution?

**Comment by Carloswaldo** [comment]
I have the exact same issue.

**Comment by naushrambo** [comment]
There is a little annoying solution, that i am using since 2 month and it always works.
1) login with the yowsup cli .
2) login
3) \disconnect
 repeat step 2 and 3 repeatedly until it resolves. 
it will auto generate the key.
maybe you have to try 50 to 100 times to solve it keep patience , it will work. 
Try deleting the .yowsup folder, and then try again.

Best Of Luck

**Comment by maxi7587** [comment]
I have exactly the same issue. Already removed `axolotl.db` from `.config/yowsup/{phone_number}` and built yowsup from master branch, but keep getting the same error when fetching messages. Will try the yowsup-cli solution and come back with the results.
