### ISSUE TITLE
WeeChat whatsapp.py problem

### ISSUE THREAD

**Issue by Fibrasek** [tgalal/yowsup#2589]
Hello guys,

I am trying to use the following plugin with `weechat`, but I keep running into the this problem:
```
         │14:53:15     | python: loading script "/home/fibrasek/.weechat/python/autoload/whatsapp.py"
         │14:53:16     | python: stdout/stderr (?): Package python-yowsup (yowsup) must be installed to use whatsapp protocol.
         │14:53:16     | python: stdout/stderr (?): Get yowsup with your package manager, or at this URL: https://github.com/tgalal/yowsup
         │14:53:16     | python: stdout/stderr (?): Traceback (most recent call last):
         │14:53:16     | python: stdout/stderr (?):   File "/home/fibrasek/.weechat/python/autoload/whatsapp.py", line 395, in <module>
         │14:53:16     | python: stdout/stderr (?):     class Server(YowInterfaceLayer):
         │14:53:16     | python: stdout/stderr (?): NameError: name 'YowInterfaceLayer' is not defined
         │14:53:16 =!= | python: unable to parse file "/home/fibrasek/.weechat/python/autoload/whatsapp.py"
```

I have both `yowsup` and `yowsup2` installed and also tried to run the script outside of `weechat` to test.

I am not a Python developer, so I'm a bit confused, hope you can help :)

**Comment by alexvong1995** [comment]
In general, please report plugin issues to the plugin developers instead of reporting it here, because we don't write the plugin - we don't know how to fix it.

Looking at the error `NameError: name 'YowInterfaceLayer' is not defined`, I guess the problem is that there was an API change in yowsup which removed `YowInterfaceLayer`, causing the error.
