### ISSUE TITLE
recommanded GNU/Linux client

### ISSUE THREAD

**Issue by dfroger** [tgalal/yowsup#2663]
Is there any recommanded GNU/Linux client? (I'm using Debian 9).

(I was planning to use this [weechat plugin](https://github.com/weechat/scripts/blob/master/python/whatsapp.py), but it [needs update](https://github.com/weechat/scripts/issues/332) for the version `3.0.0`.)

**Comment by stv0g** [comment]
This is not an issue and not directly related to yowsup.

Please close the issue

**Comment by dfroger** [comment]
"Issues" on github are often used to discuss, not just to for bugs. Where can discussion take place?

**Comment by alexvong1995** [comment]
@dfroger

I agree, since there isn't a mailing list or forum for yowsup. I think it's
fine to discuss it here.

Regarding GNU/Linux client, do you use emacs? I have written a very simple
emacs yowsup mode (not released yet). It was written for yowsup 2 though, so I
need to modernize it to make it work for yowsup 3.
