### ISSUE TITLE
register help

### ISSUE THREAD

**Issue by kylonrizoki** [tgalal/yowsup#3083]
i am trying to register with emulator 

but it show BAN after type a name in whatsapp

i tried more than 10 emulator, and i tried 50 different IP with custom VPN

do you have any solution ?

in these days.. is whatsapp banned you when register ?

**Comment by halper03** [comment]
Merhabalar bu projede görüşmek istediğim 1-2 şey var.
Müsait zamanınızda görüşebilir miyiz?
Kolay gelsin.

**Comment by ermancanitatli** [comment]
It is not related to the ip address. 
That's why vpn won't work. 
Signing up for Yowsup is not healthy right now. 
WhatsApp somehow understands this situation.

- Usually, Whatsapp numbers are no longer banned when register
- Usually, your number will be banned when you log in after registering on whatsapp with yowsup.

**Comment by slaiddominio** [comment]
@kylonrizoki You can contact me, I have the solution to your problem.

Telegram: LeandroDeFranca

**Comment by tgalal** [comment]
https://github.com/tgalal/yowsup/wiki/FAQ#how-do-i-prevent-banning-of-my-account
