### ISSUE TITLE
Doubts on my development

### ISSUE THREAD

**Issue by metafisica** [tgalal/yowsup#550]
Dear Tarek,

Not sure if what i'm asking is an issue, forgive if it's not.
I'm doing a little development on my own (and doing a crash course on python as it goes).
My project (which I'll send you as soon as it's finished) lacks two things:

- What is the best way to recover from a disconnection event, should I simply restart (and reconnect) or is there any other (simpler) way to do it.

- If I have my app listening how do I send a message without disconnecting the listening thread. I've thought of two ways: sending the message to send through a socket (and have it sent) or writing the message to a file and have the main thread check for that file every now and then.

Please share your insights with me.

THX a lot in advance.

Yours, metafisica.

**Comment by UndeadLeech** [comment]
I think I might be able to help you with the disconnecting issue. (Copied this solution from another issue because it's working great for me)

http://pastebin.com/NbRzkvSZ

This might help, or it might not. For me it works perfectly, whenever I get disconnected it connects back and if that's not working it exits and displays why.

**Comment by metafisica** [comment]
I think i've figured a workaround. 
THX to Tarek and Underleech.

**Comment by mode2k** [comment]
Can you share your reconnect solution, please? 
stack.loop() does not exit on a disconnect?!?
