### ISSUE TITLE
new update/ today ... block number if send 30-70 msg

### ISSUE THREAD

**Issue by mofakfree** [tgalal/yowsup#63]
The block numbers after sending about 20- 70 different number !!!!!
What are your experiences and your knowledge?About this update
##

**Comment by dllort** [comment]
Hi @Timespace7 @Akuka @WhiteHatAlister, I'm interested in a way to get some numbers, I have another approach to increase the limits but my real problem to test it is the provisioning of numbers. Can you contact me please? My email is in my profile. Thanks in advance...

**Comment by hottmex** [comment]
The way whatsapp blocks is very simple. First they do not look to determine if the message content is "spam" or otherwise, second, they dont care about the ip address. Many cellphones on a single provider or tower more than likely share the same public IP because its "NAT". Imagine they block an ip and block 100,000 users for one sending "SPAM".?!?  Its quite simple what they do. If a recently registered account sends more than between 17 to 20 messages to contacts that are not synced in its contact list "Not actual contacts", it blocks that channel. Period. Accounts that are well aged as in a year or more, and have sent a good deal of traffic to actual contacts are given slightly more slack but also eventually get blocked. I dont believe there is anyway around the block other than having many, many, many channels and always adding new-ones. If someone sends to contacts that they have synced, they can send the same message a million times in 1 day and they will not get blocked. So it doesnt matter the timing between messages, the faking of "writing message" handshake, the ip address or any other trick. Send more than 17 messages on a new account to contacts that are not in your contacts, have not been synced, and have not added your number will get that line blocked period.

**Comment by WhiteHatAlister** [comment]
@hottmex amen. Thanks for putting up some common sense here. I regret offering phone numbers in the past.

**Comment by ashishnetworks** [comment]
There is a trick. For never getting block
1. Never send any message to user before you receives from her
2. You can send single reply to single message
3. So if a user sends you 1 million message you can send her 1 million reply that too without getting blocked.

[Above steps also prevents spams for users. And I tried it  sending thousands message and it worked without getting blocked

**Comment by suraj-mahajan** [comment]
<img src="https://assets-cdn.github.com/images/icons/emoji/unicode/1f4a9.png">

**Comment by charanjit-singh** [comment]
I can send messages to 2000 people at once, without getting banned, using a simple strategy.

Sync Phone numbers before you send messages and Ack After every 10-20 MEssages + Sending Typing ,Paused Signals with them,

**Comment by bng5** [comment]
Is it possible to send Typing, Paused Signals with Yowsup 2?

**Comment by charanjit-singh** [comment]
Yes
