### ISSUE TITLE
Use YowStackBuilder in echo and send clients

### ISSUE THREAD

**Issue by ncri** [tgalal/yowsup#639]
I just sent a message using the CLI. Worked fine, but I got this warning:

```
WARNING:yowsup.stacks.yowstack:Implicit declaration of parallel layers in a tuple is deprecated, pass a YowParallelLayer instead
```

Any idea how to fix it?
##

**Comment by overallduka** [comment]
+1

**Comment by tgalal** [comment]
It's a reminder to use [YowStackBuilder](https://github.com/tgalal/yowsup/blob/master/yowsup/demos/cli/stack.py#L16). I probably forgot to do so in echo and send client.

**Comment by mohammadwali** [comment]
Is there any solution for now, or do i need to wait for the next update ?

**Comment by blackjack4494** [comment]
Since you can use the application in the way it was made for expect it to be fixed most likely in next the update.
The Warning is just a Reminder as tgalal mentioned it. But if you having problem with showing you this warning you can disable it (but i would not recommend it):
https://github.com/tgalal/yowsup/blob/master/yowsup/stacks/yowstack.py#L176
You should then comment the whole def _construct out by using """ (shift+2)
so: 
"""
def _construct
....code....
self.__stackInstances[i].setLayers(upperLayer, lowerLayer)
"""
