### ISSUE TITLE
Accounts blocked by WhatsApp

### ISSUE THREAD

**Issue by Udirley** [tgalal/yowsup#657]
Hello everybody
Yesterday forth had 6 accounts blocked by WhatsApp.
I make it clear that we are not using WhatsApp to make advertisements, these accounts are used by radio stations to receive musical requests of its listeners and also receive feedback on how they are transit visa by listeners.
Highlight some accounts use the Yowsup and others use the WhatsAPI-Official and had locks on both.
Is there anything we can do to prevent this?
I thank the attention.

**Comment by blackjack4494** [comment]
Well. It's quite easy. It's not spam but I guess you are getting a lot of messages. Automated Systems are not allowed. As well as having too many chats with people you don't have in your contact list (same goes for those - they have to add you in their contacts).
Also you should use broadcasting.
http://www.whatsapp.com/faq/en/general/23154266
https://www.whatsapp.com/faq/en/general/28030003

**Comment by Udirley** [comment]
Thanks for the reply.

Listeners certainly has the radio number registered on their agenda, as in mobile application he must register first to post messages.
The system is that there is an agenda to add listeners.

I have 3 questions and would appreciate if you can answer me:
1. Is there any way to have an agenda within this API to add the listeners?
2. Is there any special license to work in this way through WhatsApp?
3. What do you mean with respect to broadcasting use?

thank you very much

**Comment by blackjack4494** [comment]
I will try to answer to it tomorrow.
Right now I can tell you there is no license offered by WhatsApp. When I understand correctly you got a smartphone app? So you actually can use xmpp (native/basic version of what WA is using - FunXmpp. It does not belong to yowsup then anymore but I can send you private message about it if you are interested. 
For now I need to sleep.

**Comment by Udirley** [comment]
Personal how to add contacts in the phonebook using the code?
I believe that this is the reason why I am being blocked. All my clients have my number on their agendas but I do not because they do not know how to attach them on the agenda using the code.
Thank attention.

**Comment by tgalal** [comment]
to sync contacts using yowsup demos:
```
yowsup-cli demos -c /path/to/config --yowsup
/L
/contacts sync number1,number2,number3,number4...
```

**Comment by erickc55** [comment]
I had the same problem Udiley, I'm working for a radio station too and whatsapp blocked the number...
And don't know why, cause I only sent a reply, just for who sent a traffic information or asked for a sound, all right I made a auto reply just saying thanks for participate, in most part the same text, sometimes putting the name in midlle of text

I sent a email to whatsapp team, and I waiting the unblock, I'm praying to be soon.

Udiley, did you find a solution? Did whatsapp team unblocked your account soon? How long they answer?

Thanks for attention

**Comment by t0rr3sp3dr0** [comment]
I did a system that send the grades to the students of my school and my account had been blocked too. Initially the account was blocked because I was sending too many messages with exactly same content, I tried to fix it putting an aleatory number on the end of the message, but I think it didn't work very well, cause my account was blocked temporarily 5 times and finally blocked permanently. Then I used another number and more one time the account was blocked, but this time was because I was sending messages to too many people that didn't have my phone number in their contacts, this time the account was blocked permanently without temporarily blocks. After some time trying to figure out how to solve both problems I think I did it by sending messages via broadcast. Because if the person doesn't have my phone number in his contacts the message will not be delivered and WhatsApp will not detect it as SPAM, and I can send the same message to a lot of people that it will not be identified as well. And just to be sure that my account won't be blocked again I will implement the contact sync previously mentioned. I've sent an e-mail to WhatsApp support unblock my account too, two days ago, and I'm waiting for the answer, while it doesn't happen I'm using another number.

**Comment by glenn1001** [comment]
@t0rr3sp3dr0 can you tell me if it's still working (sending the messages to everyone with the broadcast method)
or did whatsapp ban you for sending these messages with the broadcast message?

**Comment by erickc55** [comment]
The persons who you gonna send with broadcast have your number in their contact list?

**Comment by glenn1001** [comment]
@erickc55 Yes, everyone who I send a message have my number in their contact list. I want to use the Whatsapp API for sending the users newsletters. The users first need to send me a message (something like "... on") to subscribe themself to the newsletter or to unsubscribe ("... off") themself from the newsletter.

**Comment by Udirley** [comment]
This question of blocking almost has no solution, I've tried everything:
- I do the sync contacts, I am sure that all of the calendar numbers are synchronized.
- Before sending check that contact has active WhatsApp.
- Do not send repeated messages.
- Before sending I simulate "typing ..." pause "typing ..." with varying time intervals.
- Do not send advertising or spam, only replies to messages from listeners.
- I maintain the version, device model updated in API.
I work with several radio stations, yet occasionally I have blocked numbers.
Sometimes I send an email to them and they unlock at other times I was not met.
For a radio station it is easy to release a new number in two days listeners have started to use the new number, but for other segments it is more difficult.
Today I am using ChatAPI, but the blockage occurs in the same way.

a hug
