### ISSUE TITLE
Use yowsup cli-demo with Raw_input in Python with Bash command.

### ISSUE THREAD

**Issue by TheCrow** [tgalal/yowsup#725]
I would like to enter an phone number with Raw_Input and use this variable in my bash command for sending a whatsapp message. I cannot get this working. Without the RAW Input, it works. I use Python 2.7 on Mac OSX see my script:

import mechanize
import os
Phonenumber = raw_input("Number?)
os.system("yowsup-cli demos --login PHONE:PASSWORD= --send '$Phonenumber' 'MESSAGE'")

**Comment by tgalal** [comment]
I don't understand, that's not even valid python syntax for what you are trying to do

**Comment by geltix** [comment]
I'm interested in the same something like 
yowsup-cli demos --yowsup --config config.src /L /message send 4912345678 Hello

**Comment by geltix** [comment]
I will contest my own: Sending Whatsapps Works fine like this:
/yowsup-cli demos --config config.src -s 4912345678 testmessage

But I didn't find anything about listening.
I need to conenct to whatsapp and copy all messages received since last login to a textfile - after disconnect  - something similar like sending but for listening. Great would be if it logsout after reading all messages so I can run it from bash every x minutes.

**Comment by tgalal** [comment]
@geltix what you want i an

**Comment by maruen** [comment]
Im also looking for getting the messages by a shell command, @tgalal  why did you closed this issue without any answer or tip on how to do that?

**Comment by felipe010203** [comment]
from subprocess import call

number _destinaction = 572222222222
message = "Hello"
call("yowsup-cli demos --login 575555555555:password --send " +number _destinaction+" "+ message , shell=True)

Send messages from python
