### ISSUE TITLE
Tokens update

### ISSUE THREAD

**Issue by catch2patch** [tgalal/yowsup#814]
Hey, does anybody know if WhatsApp have updated tokens recently?
I've found v. 2.12.82 tokens updated 3 days ago:
https://github.com/mgp25/Chat-API/blob/master/src/Constants.php
https://github.com/mgp25/Chat-API/blob/master/src/token.php
But they seem to be outdated too and unfortunately there are no android version tokens there.
Could somebody check please?
BTW, maybe this link can help: https://coderus.openrepos.net/whitesoft/whatsapp_scratch
##

**Comment by mgp25** [comment]
Chat API is up to date and its working.

Better post your debug log so we can see whats happening to you

**Comment by dedmen** [comment]
#824

**Comment by catch2patch** [comment]
Nah, unfortunately that haven't helped. Guess something has been changed in the protocol. It's not possible to send messages to 8 new contacts via API but it is possible to do via the app. So something is wrong with the API..
I'll try to get deeper but I am not sure if I succeed.

**Comment by tgalal** [comment]
I don't understand what the issue is?

**Comment by mgp25** [comment]
@catch2patch API its not perfect there are things we haven't implemented and that makes API very easy to detect, anyway... if you are trying to send messages to semi-random users (that haven't your number added you will be probably blocked), + that number was registered recently.

Is not good to compare app and API because it isn't the same, and that doesn't mean the API works bad, it means there are thing to be done yet. FYI, WA protocol hasn't changed, so don't search deeper.

If you are using API for personal stuff is barely impossible to get your account blocked. Once i got the chance to read an email from WA engineers, they have pretty good algorithm to prevent spam and it takes lots of things and data to consider.

@catch2patch i recommend you to chat with your friends, family, etc and you will see you wont be blocked again, even you can do domotic bots or similar.

Best regards
