### ISSUE TITLE
GPIO input

### ISSUE THREAD

**Issue by Francisco661** [tgalal/yowsup#963]
Hi everybody,

I am trying to use GPIO inputs of a Raspberry to send a message using yowsup, I have tried many ways but I can't did it.
I'll be very grateful if someone help me.

**Comment by jlguardi** [comment]
I think it's not the focus of this repository. The question is about raspberry instead of yowsup. However, I'll try to answer:

Try this: http://stackoverflow.com/questions/16143842/raspberry-pi-gpio-events-in-python/18596063#18596063

And call with os.system the command "yowsup-cli demos -s dest "msg" -c config.file"

**Comment by Francisco661** [comment]
thanks!! it is working.=)
